import React, { createContext, useState, useContext, useEffect } from 'react';

export type Language = 'de' | 'en' | 'pt' | 'fr' | 'es' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    'inv.title': 'Unsere Fahrzeuge',
    'inv.subtitle': 'Entdecken Sie unsere große Auswahl an geprüften Premium-Fahrzeugen, perfekt abgestimmt auf Ihre Bedürfnisse.',
    'inv.search': 'Marke oder Modell suchen...',
    'inv.cars': 'Fahrzeuge',
    'inv.car': 'Fahrzeug',
    'inv.filtered': 'Gefilterte Ergebnisse',
    'inv.all': 'Alle verfügbaren Fahrzeuge',
    'inv.sort.newest': 'Neueste zuerst',
    'inv.sort.price_asc': 'Preis aufsteigend',
    'inv.sort.price_desc': 'Preis absteigend',
    'inv.sort.mileage': 'Kilometerstand',
    'inv.sort.year': 'Baujahr',
    'inv.filter': 'Filter',
    'inv.reset': 'Alle zurücksetzen',
    'inv.apply': 'Anwenden',
    'inv.empty.title': 'Keine Fahrzeuge gefunden',
    'inv.empty.desc': 'Versuchen Sie, Ihre Suchkriterien anzupassen oder alle Filter zurückzusetzen.',
    'inv.empty.action': 'Filter zurücksetzen',
    'inv.chip.make': 'Marke',
    'inv.chip.price': 'Preis',
    'inv.chip.year': 'Jahr',
    'inv.chip.fuel': 'Kraftstoff',
    'inv.chip.gear': 'Getriebe',
    'inv.chip.type': 'Typ',
    'inv.chip.today': 'heute',

    'nav.home': 'Startseite',
    'nav.vehicles': 'Fahrzeuge',
    'nav.financing': 'Finanzierung',
    'nav.tradein': 'Inzahlungnahme',
    'nav.exclusive': 'Exklusive Angebote',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.philosophy': 'Philosophie',
    'nav.history': 'Geschichte',
    'header.call': 'Rufen Sie uns an',
    'header.menu': 'Menü',
    'header.consultation': 'Beratung',
    'footer.tagline': 'Nordhessen Automobile steht für erstklassige Premium-Fahrzeuge, absolute Transparenz und absolute Leidenschaft für Perfektion. Entdecken Sie Qualität in jedem Detail.',
    'footer.legal': 'Rechtliches',
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.contact': 'Kontakt',
    'footer.hours': 'Mo-Fr 9:00-18:00 | Sa 10:00-16:00',
    'home.hero.title': 'Premium Fahrzeuge für höchste Ansprüche',
    'home.hero.subtitle': 'Entdecken Sie unsere exklusive Auswahl an Premium-Fahrzeugen. BMW, Mercedes-Benz, Audi, Porsche und mehr.',
    'home.brands.label': 'Premium Marken',
    'home.brands.title': 'Exklusive Auswahl',
    'home.brands.subtitle': 'Qualitätsfahrzeuge der renommiertesten Hersteller Deutschlands, präsentiert in einer High-End-Umgebung für höchste Ansprüche.',
    'home.services.label': 'Unsere Leistungen',
    'home.services.title': 'Premium Service',
    'home.services.subtitle': 'Wir bieten Ihnen ein ganzheitliches Erlebnis rund um den Fahrzeugkauf. Profitieren Sie von unseren maßgeschneiderten Dienstleistungen.',
    'home.services.fin.title': 'Finanzierung',
    'home.services.fin.desc': 'Maßgeschneiderte Finanzierungs- und Leasingangebote mit absoluten Top-Konditionen für Ihr Traumauto.',
    'home.services.gar.title': 'Premium Garantie',
    'home.services.gar.desc': 'Umfassende Garantiepakete für sorgenfreies Fahren. Wir sichern Ihr Fahrzeug zuverlässig ab.',
    'home.services.trade.title': 'Inzahlungnahme',
    'home.services.trade.desc': 'Faire und transparente Bewertung Ihres aktuellen Fahrzeugs für eine unkomplizierte Inzahlungnahme.',
    'home.stats.customers': 'Zufriedene Kunden',
    'home.stats.experience': 'Jahre Erfahrung',
    'home.stats.quality': 'Geprüfte Qualität',
    'home.featured.label': 'Unsere Auswahl',
    'home.featured.title': 'Top Fahrzeuge',
    'home.featured.subtitle': 'Handverlesen und geprüft — unsere neuesten Premium-Modelle',
    'home.featured.viewAll': 'Alle ansehen',
    'home.features.q.title': 'Geprüfte Qualität',
    'home.features.q.desc': 'Jedes Fahrzeug durchläuft eine 150-Punkte-Inspektion durch unsere Experten.',
    'home.features.c.title': 'Beste Konditionen',
    'home.features.c.desc': 'Transparente Preise und flexible Finanzierungsmöglichkeiten.',
    'home.features.g.title': 'Garantie inklusive',
    'home.features.g.desc': 'Umfassender Schutz auf alle Fahrzeuge — für Ihre Sicherheit.',
    'home.features.f.title': 'Einfache Finanzierung',
    'home.features.f.desc': 'Flexible Raten, schnelle Genehmigung, maßgeschneiderte Lösungen.',
    'home.phi.label': 'Unsere Philosophie',
    'home.phi.title': 'Mehr als nur Automobile. Ihre Mobilität.',
    'home.phi.desc1': 'Bei Nordhessen Automobile steht Vertrauen an erster Stelle. Wir bieten Ihnen absolute Transparenz, ehrliche Beratung und erstklassigen Service – von der ersten Besichtigung bis zur Schlüsselübergabe.',
    'home.phi.desc2': 'Jedes Fahrzeug in unserem Bestand wird sorgfältig geprüft und stammt direkt aus unserem Live-Inventar. Wir garantieren Ihnen gepflegte Premium-Fahrzeuge mit lückenloser Historie und höchster Qualität.',
    'home.phi.live': 'Live',
    'home.phi.live_desc': 'Aktueller Bestand',
    'home.phi.transparency': 'Maximale',
    'home.phi.transparency_desc': 'Kauf-Transparenz',
    'home.why.label': 'Unsere Stärken',
    'home.why.title': 'Warum Nordhessen Automobile?',
    'home.why.subtitle': 'Vertrauen, Qualität und Service — die Grundpfeiler unseres Erfolgs',
    'home.cta.label': 'Bereit für Ihren Neuen?',
    'home.cta.title1': 'Ihr Traumauto',
    'home.cta.title2': 'wartet bereits.',
    'home.cta.desc': 'Entdecken Sie unsere Premium-Auswahl und finden Sie das perfekte Fahrzeug, das Ihren höchsten Ansprüchen gerecht wird.',
    'home.cta.button': 'Fahrzeuge entdecken',
    'home.no_cars': 'Derzeit sind keine Fahrzeuge verfügbar.',
    'card.year': 'Jahr',
    'card.km': 'Km',
    'card.fuel': 'Kraftstoff',
    'card.gearbox': 'Getriebe',
    'card.details': 'Details ansehen',
    'scroll.elegance': 'ELEGANZ TRIFFT PERFORMANCE',
    'scroll.elegance_desc': 'Die perfekte Fusion aus Sportlichkeit und Alltagstauglichkeit. Ein viertüriges Coupé, das jede Fahrt zum Erlebnis macht.',
    'scroll.design': 'AERODYNAMISCH GEFORMT',
    'scroll.design_title': 'Design',
    'scroll.design_desc': 'Rahmenlose Türen, fließende Dachlinie und die ikonische Niere. Jedes Detail für präzise Luftdurchdringung gestaltet.',
    'scroll.engine': 'TURBOCHARGED EFFIZIENZ',
    'scroll.engine_title': 'Motor',
    'scroll.engine_desc': 'Kraftvoller Motor für pure Fahrdynamik und Effizienz auf jeder Fahrt. Perfekt abgestimmtes Getriebe für ein aufregendes Fahrerlebnis.',
    'scroll.performance': 'DYNAMISCHES FAHRERLEBNIS',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Außergewöhnliche Beschleunigung und präzises Handling dank fortschrittlicher M Sport Fahrwerkstechnologie und variabler Sportlenkung.',
    'scroll.nav.start': 'Start',
    'scroll.nav.design': 'Design',
    'scroll.nav.engine': 'Motor',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Standort // Kassel',
    'scroll.cta.title1': 'Finden Sie Ihr',
    'scroll.cta.title2': 'Traumauto',
    'scroll.cta.desc': 'Premium-Fahrzeuge, persönliche Beratung und erstklassiger Service. Entdecken Sie unsere aktuelle Kollektion.',
    'scroll.cta.button': 'Alle Modelle',
    'scroll.cta.stat1': 'Geprüft',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Qualität',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Service',
  },
  en: {
    'inv.title': 'Our Vehicles',
    'inv.subtitle': 'Discover our large selection of tested premium vehicles, perfectly tailored to your needs.',
    'inv.search': 'Search make or model...',
    'inv.cars': 'Vehicles',
    'inv.car': 'Vehicle',
    'inv.filtered': 'Filtered results',
    'inv.all': 'All available vehicles',
    'inv.sort.newest': 'Newest first',
    'inv.sort.price_asc': 'Price ascending',
    'inv.sort.price_desc': 'Price descending',
    'inv.sort.mileage': 'Mileage',
    'inv.sort.year': 'Year',
    'inv.filter': 'Filter',
    'inv.reset': 'Reset all',
    'inv.apply': 'Apply',
    'inv.empty.title': 'No vehicles found',
    'inv.empty.desc': 'Try adjusting your search criteria or reset all filters.',
    'inv.empty.action': 'Reset filters',
    'inv.chip.make': 'Make',
    'inv.chip.price': 'Price',
    'inv.chip.year': 'Year',
    'inv.chip.fuel': 'Fuel',
    'inv.chip.gear': 'Gearbox',
    'inv.chip.type': 'Type',
    'inv.chip.today': 'today',

    'nav.home': 'Home',
    'nav.vehicles': 'Vehicles',
    'nav.financing': 'Financing',
    'nav.tradein': 'Trade-In',
    'nav.exclusive': 'Exclusive Offers',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.philosophy': 'Philosophy',
    'nav.history': 'Our Story',
    'header.call': 'Call us',
    'header.menu': 'Menu',
    'header.consultation': 'Consultation',
    'footer.tagline': 'Nordhessen Automobile stands for first-class premium vehicles, absolute transparency and absolute passion for perfection. Discover quality in every detail.',
    'footer.legal': 'Legal',
    'footer.impressum': 'Imprint',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact',
    'footer.hours': 'Mon-Fri 9:00-18:00 | Sat 10:00-16:00',
    'home.hero.title': 'Premium Vehicles for Highest Standards',
    'home.hero.subtitle': 'Discover our exclusive selection of premium vehicles. BMW, Mercedes-Benz, Audi, Porsche and more.',
    'home.brands.label': 'Premium Brands',
    'home.brands.title': 'Exclusive Selection',
    'home.brands.subtitle': 'Quality vehicles from Germany\'s most renowned manufacturers, presented in a high-end environment for the highest demands.',
    'home.services.label': 'Our Services',
    'home.services.title': 'Premium Service',
    'home.services.subtitle': 'We offer you a holistic experience around vehicle purchasing. Benefit from our tailored services.',
    'home.services.fin.title': 'Financing',
    'home.services.fin.desc': 'Tailored financing and leasing offers with absolute top conditions for your dream car.',
    'home.services.gar.title': 'Premium Warranty',
    'home.services.gar.desc': 'Comprehensive warranty packages for worry-free driving. We secure your vehicle reliably.',
    'home.services.trade.title': 'Trade-In',
    'home.services.trade.desc': 'Fair and transparent assessment of your current vehicle for an uncomplicated trade-in.',
    'home.stats.customers': 'Happy Customers',
    'home.stats.experience': 'Years of Experience',
    'home.stats.quality': 'Tested Quality',
    'home.featured.label': 'Our Selection',
    'home.featured.title': 'Top Vehicles',
    'home.featured.subtitle': 'Hand-picked and tested — our latest premium models',
    'home.featured.viewAll': 'View all',
    'home.features.q.title': 'Tested Quality',
    'home.features.q.desc': 'Every vehicle undergoes a 150-point inspection by our experts.',
    'home.features.c.title': 'Best Conditions',
    'home.features.c.desc': 'Transparent prices and flexible financing options.',
    'home.features.g.title': 'Warranty Included',
    'home.features.g.desc': 'Comprehensive protection on all vehicles — for your safety.',
    'home.features.f.title': 'Easy Financing',
    'home.features.f.desc': 'Flexible rates, quick approval, custom solutions.',
    'home.phi.label': 'Our Philosophy',
    'home.phi.title': 'More than just automobiles. Your mobility.',
    'home.phi.desc1': 'Nordhessen Automobile stands for absolute transparency, honest advice and first-class customer service. We understand that buying a vehicle is a matter of trust.',
    'home.phi.desc2': 'Every vehicle in our showroom is sourced live from our current inventory and carefully checked to meet our high standards. Discover well-maintained models with a guaranteed history.',
    'home.phi.live': 'Live',
    'home.phi.live_desc': 'Current Inventory',
    'home.phi.transparency': 'Maximum',
    'home.phi.transparency_desc': 'Buying Transparency',
    'home.why.label': 'Our Strengths',
    'home.why.title': 'Why Nordhessen Automobile?',
    'home.why.subtitle': 'Trust, quality and service — the cornerstones of our success',
    'home.cta.label': 'Ready for your new one?',
    'home.cta.title1': 'Your dream car',
    'home.cta.title2': 'is already waiting.',
    'home.cta.desc': 'Discover our premium selection and find the perfect vehicle that meets your highest demands.',
    'home.cta.button': 'Discover Vehicles',
    'home.no_cars': 'Currently no vehicles available.',
    'card.year': 'Year',
    'card.km': 'Mileage',
    'card.fuel': 'Fuel',
    'card.gearbox': 'Gearbox',
    'card.details': 'View Details',
    'scroll.elegance': 'ELEGANCE MEETS PERFORMANCE',
    'scroll.elegance_desc': 'The perfect fusion of sportiness and everyday practicality. A four-door coupé that turns every drive into an experience.',
    'scroll.design': 'SCULPTED FOR AERODYNAMICS',
    'scroll.design_title': 'Design',
    'scroll.design_desc': 'Frameless doors, flowing roofline, and the iconic kidney grille. Every detail designed to cut through the air with precision.',
    'scroll.engine': 'TURBOCHARGED EFFICIENCY',
    'scroll.engine_title': 'Engine',
    'scroll.engine_desc': 'Powerful engine delivering pure driving dynamics and efficiency on every journey. Perfectly matched transmission for an exhilarating drive.',
    'scroll.performance': 'DYNAMIC DRIVING EXPERIENCE',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Exceptional acceleration and precise handling thanks to advanced M Sport suspension technology and variable sport steering.',
    'scroll.nav.start': 'Start',
    'scroll.nav.design': 'Design',
    'scroll.nav.engine': 'Engine',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Location // Kassel',
    'scroll.cta.title1': 'Find Your',
    'scroll.cta.title2': 'Dream Car',
    'scroll.cta.desc': 'Premium vehicles, personal advice and first-class service. Discover our current collection.',
    'scroll.cta.button': 'All Models',
    'scroll.cta.stat1': 'Tested',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Quality',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Service',
  },
  pt: {
    'inv.title': 'Os Nossos Veículos',
    'inv.subtitle': 'Descubra a nossa grande seleção de veículos premium testados, perfeitamente adaptados às suas necessidades.',
    'inv.search': 'Pesquisar marca ou modelo...',
    'inv.cars': 'Veículos',
    'inv.car': 'Veículo',
    'inv.filtered': 'Resultados filtrados',
    'inv.all': 'Todos os veículos disponíveis',
    'inv.sort.newest': 'Mais recentes',
    'inv.sort.price_asc': 'Preço ascendente',
    'inv.sort.price_desc': 'Preço descendente',
    'inv.sort.mileage': 'Quilometragem',
    'inv.sort.year': 'Ano',
    'inv.filter': 'Filtro',
    'inv.reset': 'Repor tudo',
    'inv.apply': 'Aplicar',
    'inv.empty.title': 'Nenhum veículo encontrado',
    'inv.empty.desc': 'Tente ajustar os seus critérios de pesquisa ou reponha todos os filtros.',
    'inv.empty.action': 'Repor filtros',
    'inv.chip.make': 'Marca',
    'inv.chip.price': 'Preço',
    'inv.chip.year': 'Ano',
    'inv.chip.fuel': 'Combustível',
    'inv.chip.gear': 'Caixa',
    'inv.chip.type': 'Tipo',
    'inv.chip.today': 'hoje',

    'nav.home': 'Início',
    'nav.vehicles': 'Veículos',
    'nav.financing': 'Financiamento',
    'nav.tradein': 'Retoma',
    'nav.exclusive': 'Ofertas Exclusivas',
    'nav.about': 'Sobre nós',
    'nav.contact': 'Contacto',
    'nav.philosophy': 'Filosofia',
    'nav.history': 'Nossa História',
    'header.call': 'Ligue-nos',
    'header.menu': 'Menu',
    'header.consultation': 'Consultoria',
    'footer.tagline': 'Nordhessen Automobile representa veículos premium de primeira classe, transparência absoluta e paixão absoluta pela perfeição. Descubra a qualidade em cada detalhe.',
    'footer.legal': 'Legal',
    'footer.impressum': 'Aviso Legal',
    'footer.privacy': 'Privacidade',
    'footer.contact': 'Contacto',
    'footer.hours': 'Seg-Sex 9:00-18:00 | Sáb 10:00-16:00',
    'home.hero.title': 'Veículos Premium para os mais Altos Padrões',
    'home.hero.subtitle': 'Descubra a nossa seleção exclusiva de veículos premium. BMW, Mercedes-Benz, Audi, Porsche e mais.',
    'home.brands.label': 'Marcas Premium',
    'home.brands.title': 'Seleção Exclusiva',
    'home.brands.subtitle': 'Veículos de qualidade dos fabricantes mais conceituados da Alemanha, apresentados num ambiente de alta gama para as mais elevadas exigências.',
    'home.services.label': 'Nossos Serviços',
    'home.services.title': 'Serviço Premium',
    'home.services.subtitle': 'Oferecemos-lhe uma experiência holística em torno da compra de veículos. Beneficie dos nossos serviços personalizados.',
    'home.services.fin.title': 'Financiamento',
    'home.services.fin.desc': 'Ofertas de financiamento e leasing personalizadas com as melhores condições para o seu carro de sonho.',
    'home.services.gar.title': 'Garantia Premium',
    'home.services.gar.desc': 'Pacotes de garantia abrangentes para uma condução sem preocupações. Seguramos o seu veículo de forma fiável.',
    'home.services.trade.title': 'Retoma',
    'home.services.trade.desc': 'Avaliação justa e transparente do seu veículo atual para uma retoma descomplicada.',
    'home.stats.customers': 'Clientes Satisfeitos',
    'home.stats.experience': 'Anos de Experiência',
    'home.stats.quality': 'Qualidade Testada',
    'home.featured.label': 'Nossa Seleção',
    'home.featured.title': 'Top Veículos',
    'home.featured.subtitle': 'Selecionados à mão e testados — os nossos modelos premium mais recentes',
    'home.featured.viewAll': 'Ver todos',
    'home.features.q.title': 'Qualidade Testada',
    'home.features.q.desc': 'Cada veículo passa por uma inspeção de 150 pontos pelos nossos especialistas.',
    'home.features.c.title': 'Melhores Condições',
    'home.features.c.desc': 'Preços transparentes e opções de financiamento flexíveis.',
    'home.features.g.title': 'Garantia Incluída',
    'home.features.g.desc': 'Proteção abrangente em todos os veículos — para sua segurança.',
    'home.features.f.title': 'Financiamento Fácil',
    'home.features.f.desc': 'Taxas flexíveis, aprovação rápida, soluções personalizadas.',
    'home.phi.label': 'Nossa Filosofia',
    'home.phi.title': 'Mais do que apenas automóveis. Sua mobilidade.',
    'home.phi.desc1': 'Nordhessen Automobile representa transparência absoluta, aconselhamento honesto e serviço ao cliente de primeira classe. Entendemos que comprar um veículo é uma questão de confiança.',
    'home.phi.desc2': 'Cada veículo no nosso showroom é obtido ao vivo a partir do nosso inventário atual e cuidadosamente verificado para cumprir os nossos elevados padrões. Descubra modelos bem mantidos com um histórico garantido.',
    'home.phi.live': 'Ao vivo',
    'home.phi.live_desc': 'Inventário Atual',
    'home.phi.transparency': 'Máxima',
    'home.phi.transparency_desc': 'Transparência de Compra',
    'home.why.label': 'Nossos Pontos Fortes',
    'home.why.title': 'Porquê Nordhessen Automobile?',
    'home.why.subtitle': 'Confiança, qualidade e serviço — os pilares do nosso sucesso',
    'home.cta.label': 'Pronto para o seu novo?',
    'home.cta.title1': 'O seu carro de sonho',
    'home.cta.title2': 'já está à espera.',
    'home.cta.desc': 'Descubra a nossa seleção premium e encontre o veículo perfeito que vai ao encontro das suas mais elevadas exigências.',
    'home.cta.button': 'Descobrir Veículos',
    'home.no_cars': 'Atualmente sem veículos disponíveis.',
    'card.year': 'Ano',
    'card.km': 'Quilometragem',
    'card.fuel': 'Combustível',
    'card.gearbox': 'Caixa',
    'card.details': 'Ver Detalhes',
    'scroll.elegance': 'ELEGÂNCIA ENCONTRA PERFORMANCE',
    'scroll.elegance_desc': 'A fusão perfeita de desportividade e praticidade quotidiana. Um coupé de quatro portas que transforma cada viagem numa experiência.',
    'scroll.design': 'ESCULPIDO PARA AERODINÂMICA',
    'scroll.design_title': 'Design',
    'scroll.design_desc': 'Portas sem moldura, linha de tejadilho fluida e a icónica grelha. Cada detalhe desenhado para cortar o ar com precisão.',
    'scroll.engine': 'EFICIÊNCIA TURBOALIMENTADA',
    'scroll.engine_title': 'Motor',
    'scroll.engine_desc': 'Motor potente que oferece dinâmica de condução pura e eficiência em cada viagem. Transmissão perfeitamente combinada para uma condução emocionante.',
    'scroll.performance': 'EXPERIÊNCIA DE CONDUÇÃO DINÂMICA',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Aceleração excecional e manuseamento preciso graças à tecnologia avançada de suspensão M Sport e direção desportiva variável.',
    'scroll.nav.start': 'Início',
    'scroll.nav.design': 'Design',
    'scroll.nav.engine': 'Motor',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Localização // Kassel',
    'scroll.cta.title1': 'Encontre o Seu',
    'scroll.cta.title2': 'Carro de Sonho',
    'scroll.cta.desc': 'Veículos premium, aconselhamento pessoal e serviço de primeira classe. Descubra a nossa coleção atual.',
    'scroll.cta.button': 'Todos os Modelos',
    'scroll.cta.stat1': 'Testado',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Qualidade',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Serviço',
  },
  fr: {
    'inv.title': 'Nos Véhicules',
    'inv.subtitle': 'Découvrez notre large sélection de véhicules premium testés, parfaitement adaptés à vos besoins.',
    'inv.search': 'Rechercher marque ou modèle...',
    'inv.cars': 'Véhicules',
    'inv.car': 'Véhicule',
    'inv.filtered': 'Résultats filtrés',
    'inv.all': 'Tous les véhicules disponibles',
    'inv.sort.newest': 'Les plus récents',
    'inv.sort.price_asc': 'Prix croissant',
    'inv.sort.price_desc': 'Prix décroissant',
    'inv.sort.mileage': 'Kilométrage',
    'inv.sort.year': 'Année',
    'inv.filter': 'Filtre',
    'inv.reset': 'Tout réinitialiser',
    'inv.apply': 'Appliquer',
    'inv.empty.title': 'Aucun véhicule trouvé',
    'inv.empty.desc': 'Essayez d\'ajuster vos critères de recherche ou réinitialisez tous les filtres.',
    'inv.empty.action': 'Réinitialiser les filtres',
    'inv.chip.make': 'Marque',
    'inv.chip.price': 'Prix',
    'inv.chip.year': 'Année',
    'inv.chip.fuel': 'Carburant',
    'inv.chip.gear': 'Boîte',
    'inv.chip.type': 'Type',
    'inv.chip.today': 'aujourd\'hui',

    'nav.home': 'Accueil',
    'nav.vehicles': 'Véhicules',
    'nav.financing': 'Financement',
    'nav.tradein': 'Reprise',
    'nav.exclusive': 'Offres Exclusives',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.philosophy': 'Philosophie',
    'nav.history': 'Notre Histoire',
    'header.call': 'Appelez-nous',
    'header.menu': 'Menu',
    'header.consultation': 'Consultation',
    'footer.tagline': 'Nordhessen Automobile est synonyme de véhicules haut de gamme de première classe, de transparence absolue et de passion absolue pour la perfection. Découvrez la qualité dans chaque détail.',
    'footer.legal': 'Mentions Légales',
    'footer.impressum': 'Empreinte',
    'footer.privacy': 'Confidentialité',
    'footer.contact': 'Contact',
    'footer.hours': 'Lun-Ven 9:00-18:00 | Sam 10:00-16:00',
    'home.hero.title': 'Véhicules Premium pour les plus Hautes Exigences',
    'home.hero.subtitle': 'Découvrez notre sélection exclusive de véhicules premium. BMW, Mercedes-Benz, Audi, Porsche et plus.',
    'home.brands.label': 'Marques Premium',
    'home.brands.title': 'Sélection Exclusive',
    'home.brands.subtitle': 'Des véhicules de qualité des constructeurs allemands les plus renommés, présentés dans un environnement haut de gamme pour les exigences les plus élevées.',
    'home.services.label': 'Nos Services',
    'home.services.title': 'Service Premium',
    'home.services.subtitle': 'Nous vous offrons une expérience holistique autour de l\'achat d\'un véhicule. Profitez de nos services sur mesure.',
    'home.services.fin.title': 'Financement',
    'home.services.fin.desc': 'Offres de financement et de leasing sur mesure aux meilleures conditions pour votre voiture de rêve.',
    'home.services.gar.title': 'Garantie Premium',
    'home.services.gar.desc': 'Packs de garantie complets pour une conduite sans soucis. Nous sécurisons votre véhicule de manière fiable.',
    'home.services.trade.title': 'Reprise',
    'home.services.trade.desc': 'Évaluation juste et transparente de votre véhicule actuel pour une reprise sans complication.',
    'home.stats.customers': 'Clients Satisfaits',
    'home.stats.experience': 'Années d\'Expérience',
    'home.stats.quality': 'Qualité Contrôlée',
    'home.featured.label': 'Notre Sélection',
    'home.featured.title': 'Top Véhicules',
    'home.featured.subtitle': 'Sélectionnés à la main et testés — nos derniers modèles premium',
    'home.featured.viewAll': 'Tout afficher',
    'home.features.q.title': 'Qualité Contrôlée',
    'home.features.q.desc': 'Chaque véhicule subit une inspection en 150 points par nos experts.',
    'home.features.c.title': 'Meilleures Conditions',
    'home.features.c.desc': 'Prix transparents et options de financement flexibles.',
    'home.features.g.title': 'Garantie Incluse',
    'home.features.g.desc': 'Protection complète sur tous les véhicules — pour votre sécurité.',
    'home.features.f.title': 'Financement Facile',
    'home.features.f.desc': 'Taux flexibles, approbation rapide, solutions personnalisées.',
    'home.phi.label': 'Notre Philosophie',
    'home.phi.title': 'Plus que des automobiles. Votre mobilité.',
    'home.phi.desc1': 'Nordhessen Automobile est synonyme de transparence absolue, de conseil honnête et de service client de premier ordre. Nous comprenons que l\'achat d\'un véhicule est une question de confiance.',
    'home.phi.desc2': 'Chaque véhicule de notre showroom provient directement de notre stock actuel et est soigneusement contrôlé pour répondre à nos normes élevées. Découvrez des modèles bien entretenus avec un historique garanti.',
    'home.phi.live': 'En direct',
    'home.phi.live_desc': 'Stock Actuel',
    'home.phi.transparency': 'Maximale',
    'home.phi.transparency_desc': 'Transparence d\'Achat',
    'home.why.label': 'Nos Atouts',
    'home.why.title': 'Pourquoi Nordhessen Automobile ?',
    'home.why.subtitle': 'Confiance, qualité et service — les piliers de notre succès',
    'home.cta.label': 'Prêt pour votre nouvelle?',
    'home.cta.title1': 'Votre voiture de rêve',
    'home.cta.title2': 'vous attend déjà.',
    'home.cta.desc': 'Découvrez notre sélection premium et trouvez le véhicule parfait qui répond à vos exigences les plus élevées.',
    'home.cta.button': 'Découvrir les véhicules',
    'home.no_cars': 'Aucun véhicule disponible actuellement.',
    'card.year': 'Année',
    'card.km': 'Kilométrage',
    'card.fuel': 'Carburant',
    'card.gearbox': 'Boîte',
    'card.details': 'Voir Détails',
    'scroll.elegance': 'L\'ÉLÉGANCE RENCONTRE LA PERFORMANCE',
    'scroll.elegance_desc': 'La fusion parfaite de sportivité et de praticité quotidienne. Un coupé quatre portes qui transforme chaque trajet en expérience.',
    'scroll.design': 'SCULPTÉ POUR L\'AÉRODYNAMIQUE',
    'scroll.design_title': 'Design',
    'scroll.design_desc': 'Portes sans cadre, ligne de toit fluide et la calandre iconique. Chaque détail conçu pour fendre l\'air avec précision.',
    'scroll.engine': 'EFFICACITÉ TURBOCOMPRESSÉE',
    'scroll.engine_title': 'Moteur',
    'scroll.engine_desc': 'Moteur puissant offrant une dynamique de conduite pure et une efficacité à chaque trajet. Transmission parfaitement adaptée pour une conduite exaltante.',
    'scroll.performance': 'EXPÉRIENCE DE CONDUITE DYNAMIQUE',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Accélération exceptionnelle et maniabilité précise grâce à la technologie avancée de suspension M Sport et à la direction sportive variable.',
    'scroll.nav.start': 'Départ',
    'scroll.nav.design': 'Design',
    'scroll.nav.engine': 'Moteur',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Emplacement // Kassel',
    'scroll.cta.title1': 'Trouvez Votre',
    'scroll.cta.title2': 'Voiture de Rêve',
    'scroll.cta.desc': 'Véhicules premium, conseil personnalisé et service de première classe. Découvrez notre collection actuelle.',
    'scroll.cta.button': 'Tous les Modèles',
    'scroll.cta.stat1': 'Contrôlé',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Qualité',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Service',
  },
  es: {
    'inv.title': 'Nuestros Vehículos',
    'inv.subtitle': 'Descubra nuestra amplia selección de vehículos premium comprobados, perfectamente adaptados a sus necesidades.',
    'inv.search': 'Buscar marca o modelo...',
    'inv.cars': 'Vehículos',
    'inv.car': 'Vehículo',
    'inv.filtered': 'Resultados filtrados',
    'inv.all': 'Todos los vehículos disponibles',
    'inv.sort.newest': 'Más recientes',
    'inv.sort.price_asc': 'Precio ascendente',
    'inv.sort.price_desc': 'Precio descendente',
    'inv.sort.mileage': 'Kilometraje',
    'inv.sort.year': 'Año',
    'inv.filter': 'Filtro',
    'inv.reset': 'Restablecer todo',
    'inv.apply': 'Aplicar',
    'inv.empty.title': 'No se encontraron vehículos',
    'inv.empty.desc': 'Intente ajustar sus criterios de búsqueda o restablezca todos los filtros.',
    'inv.empty.action': 'Restablecer filtros',
    'inv.chip.make': 'Marca',
    'inv.chip.price': 'Precio',
    'inv.chip.year': 'Año',
    'inv.chip.fuel': 'Combustible',
    'inv.chip.gear': 'Caja',
    'inv.chip.type': 'Tipo',
    'inv.chip.today': 'hoy',

    'nav.home': 'Inicio',
    'nav.vehicles': 'Vehículos',
    'nav.financing': 'Financiación',
    'nav.tradein': 'Tasación',
    'nav.exclusive': 'Ofertas Exclusivas',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.philosophy': 'Filosofía',
    'nav.history': 'Nuestra Historia',
    'header.call': 'Llámanos',
    'header.menu': 'Menú',
    'header.consultation': 'Consultoría',
    'footer.tagline': 'Nordhessen Automobile representa vehículos premium de primera clase, transparencia absoluta y pasión absoluta por la perfección. Descubre la calidad en cada detalle.',
    'footer.legal': 'Legal',
    'footer.impressum': 'Aviso Legal',
    'footer.privacy': 'Privacidad',
    'footer.contact': 'Contacto',
    'footer.hours': 'Lun-Vie 9:00-18:00 | Sáb 10:00-16:00',
    'home.hero.title': 'Vehículos Premium para las más Altas Exigencias',
    'home.hero.subtitle': 'Descubra nuestra selección exclusiva de vehículos premium. BMW, Mercedes-Benz, Audi, Porsche y más.',
    'home.brands.label': 'Marcas Premium',
    'home.brands.title': 'Selección Exclusiva',
    'home.brands.subtitle': 'Vehículos de calidad de los fabricantes más reconocidos de Alemania, presentados en un entorno de alta gama para las máximas exigencias.',
    'home.services.label': 'Nuestros Servicios',
    'home.services.title': 'Servicio Premium',
    'home.services.subtitle': 'Le ofrecemos una experiencia integral en torno a la compra de vehículos. Benefíciese de nuestros servicios personalizados.',
    'home.services.fin.title': 'Financiación',
    'home.services.fin.desc': 'Ofertas de financiación y leasing a medida con las mejores condiciones para el coche de sus sueños.',
    'home.services.gar.title': 'Garantía Premium',
    'home.services.gar.desc': 'Paquetes de garantía integrales para una conducción sin preocupaciones. Aseguramos su vehículo de forma fiable.',
    'home.services.trade.title': 'Tasación',
    'home.services.trade.desc': 'Valoración justa y transparente de su vehículo actual para una tasación sin complicaciones.',
    'home.stats.customers': 'Clientes Satisfechos',
    'home.stats.experience': 'Años de Experiencia',
    'home.stats.quality': 'Calidad Comprobada',
    'home.featured.label': 'Nuestra Selección',
    'home.featured.title': 'Top Vehículos',
    'home.featured.subtitle': 'Seleccionados y comprobados: nuestros últimos modelos premium',
    'home.featured.viewAll': 'Ver todos',
    'home.features.q.title': 'Calidad Comprobada',
    'home.features.q.desc': 'Cada vehículo se somete a una inspección de 150 puntos por parte de nuestros expertos.',
    'home.features.c.title': 'Mejores Condiciones',
    'home.features.c.desc': 'Precios transparentes y opciones de financiación flexibles.',
    'home.features.g.title': 'Garantía Incluida',
    'home.features.g.desc': 'Protección integral en todos los vehículos, para su seguridad.',
    'home.features.f.title': 'Financiación Fácil',
    'home.features.f.desc': 'Cuotas flexibles, aprobación rápida, soluciones personalizadas.',
    'home.phi.label': 'Nuestra Filosofía',
    'home.phi.title': 'Más que automóviles. Su movilidad.',
    'home.phi.desc1': 'Nordhessen Automobile es sinónimo de transparencia absoluta, asesoramiento honesto y servicio al cliente de primera clase. Entendemos que la compra de un vehículo es una cuestión de confianza.',
    'home.phi.desc2': 'Cada vehículo de nuestro showroom se obtiene en vivo de nuestro inventario actual y se revisa cuidadosamente para cumplir con nuestros altos estándares. Descubra modelos bien mantenidos con un historial garantizado.',
    'home.phi.live': 'En vivo',
    'home.phi.live_desc': 'Inventario Actual',
    'home.phi.transparency': 'Máxima',
    'home.phi.transparency_desc': 'Transparencia de Compra',
    'home.why.label': 'Nuestras Fortalezas',
    'home.why.title': '¿Por qué Nordhessen Automobile?',
    'home.why.subtitle': 'Confianza, calidad y servicio: los pilares de nuestro éxito',
    'home.cta.label': '¿Listo para tu nuevo?',
    'home.cta.title1': 'Tu coche de ensueño',
    'home.cta.title2': 'ya te está esperando.',
    'home.cta.desc': 'Descubra nuestra selección premium y encuentre el vehículo perfecto que cumpla con sus más altas exigencias.',
    'home.cta.button': 'Descubrir vehículos',
    'home.no_cars': 'Actualmente no hay vehículos disponibles.',
    'card.year': 'Año',
    'card.km': 'Kilometraje',
    'card.fuel': 'Combustible',
    'card.gearbox': 'Caja',
    'card.details': 'Ver Detalles',
    'scroll.elegance': 'LA ELEGANCIA ENCUENTRA LA PERFORMANCE',
    'scroll.elegance_desc': 'La fusión perfecta de deportividad y practicidad diaria. Un coupé de cuatro puertas que convierte cada viaje en una experiencia.',
    'scroll.design': 'ESCULPIDO PARA LA AERODINÁMICA',
    'scroll.design_title': 'Diseño',
    'scroll.design_desc': 'Puertas sin marco, línea de techo fluida y la icónica parrilla. Cada detalle diseñado para cortar el aire con precisión.',
    'scroll.engine': 'EFICIENCIA TURBOALIMENTADA',
    'scroll.engine_title': 'Motor',
    'scroll.engine_desc': 'Motor potente que ofrece dinámica de conducción pura y eficiencia en cada viaje. Transmisión perfectamente adaptada para una conducción emocionante.',
    'scroll.performance': 'EXPERIENCIA DE CONDUCCIÓN DINÁMICA',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Aceleración excepcional y manejo preciso gracias a la tecnología avanzada de suspensión M Sport y dirección deportiva variable.',
    'scroll.nav.start': 'Inicio',
    'scroll.nav.design': 'Diseño',
    'scroll.nav.engine': 'Motor',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Ubicación // Kassel',
    'scroll.cta.title1': 'Encuentra Tu',
    'scroll.cta.title2': 'Coche de Ensueño',
    'scroll.cta.desc': 'Vehículos premium, asesoramiento personal y servicio de primera clase. Descubre nuestra colección actual.',
    'scroll.cta.button': 'Todos los Modelos',
    'scroll.cta.stat1': 'Comprobado',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Calidad',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Servicio',
  },
  it: {
    'inv.title': 'I Nostri Veicoli',
    'inv.subtitle': 'Scopri la nostra vasta selezione di veicoli premium testati, perfettamente su misura per le tue esigenze.',
    'inv.search': 'Cerca marca o modello...',
    'inv.cars': 'Veicoli',
    'inv.car': 'Veicolo',
    'inv.filtered': 'Risultati filtrati',
    'inv.all': 'Tutti i veicoli disponibili',
    'inv.sort.newest': 'Più recenti',
    'inv.sort.price_asc': 'Prezzo crescente',
    'inv.sort.price_desc': 'Prezzo decrescente',
    'inv.sort.mileage': 'Chilometraggio',
    'inv.sort.year': 'Anno',
    'inv.filter': 'Filtro',
    'inv.reset': 'Reimposta tutto',
    'inv.apply': 'Applica',
    'inv.empty.title': 'Nessun veicolo trovato',
    'inv.empty.desc': 'Prova ad adattare i criteri di ricerca o reimposta tutti i filtri.',
    'inv.empty.action': 'Reimposta filtri',
    'inv.chip.make': 'Marca',
    'inv.chip.price': 'Prezzo',
    'inv.chip.year': 'Anno',
    'inv.chip.fuel': 'Carburante',
    'inv.chip.gear': 'Cambio',
    'inv.chip.type': 'Tipo',
    'inv.chip.today': 'oggi',

    'nav.home': 'Home',
    'nav.vehicles': 'Veicoli',
    'nav.financing': 'Finanziamento',
    'nav.tradein': 'Permuta',
    'nav.exclusive': 'Offerte Esclusive',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatti',
    'nav.philosophy': 'Filosofia',
    'nav.history': 'La Nostra Storia',
    'header.call': 'Chiamaci',
    'header.menu': 'Menu',
    'header.consultation': 'Consulenza',
    'footer.tagline': 'Nordhessen Automobile è sinonimo di veicoli premium di prima classe, trasparenza assoluta e passione assoluta per la perfezione. Scopri la qualità in ogni dettaglio.',
    'footer.legal': 'Legale',
    'footer.impressum': 'Note Legali',
    'footer.privacy': 'Privacy',
    'footer.contact': 'Contatti',
    'footer.hours': 'Lun-Ven 9:00-18:00 | Sab 10:00-16:00',
    'home.hero.title': 'Veicoli Premium per le più Alte Esigenze',
    'home.hero.subtitle': 'Scopri la nostra selezione esclusiva di veicoli premium. BMW, Mercedes-Benz, Audi, Porsche e altro.',
    'home.brands.label': 'Marchi Premium',
    'home.brands.title': 'Selezione Esclusiva',
    'home.brands.subtitle': 'Veicoli di qualità dei produttori più rinomati della Germania, presentati in un ambiente di fascia alta per le massime esigenze.',
    'home.services.label': 'I Nostri Servizi',
    'home.services.title': 'Servizio Premium',
    'home.services.subtitle': 'Ti offriamo un\'esperienza olistica legata all\'acquisto di un veicolo. Approfitta dei nostri servizi su misura.',
    'home.services.fin.title': 'Finanziamento',
    'home.services.fin.desc': 'Offerte di finanziamento e leasing su misura con le migliori condizioni per l\'auto dei tuoi sogni.',
    'home.services.gar.title': 'Garanzia Premium',
    'home.services.gar.desc': 'Pacchetti di garanzia completi per una guida senza pensieri. Proteggiamo il tuo veicolo in modo affidabile.',
    'home.services.trade.title': 'Permuta',
    'home.services.trade.desc': 'Valutazione equa e trasparente del tuo veicolo attuale per una permuta senza complicazioni.',
    'home.stats.customers': 'Clienti Soddisfatti',
    'home.stats.experience': 'Anni di Esperienza',
    'home.stats.quality': 'Qualità Controllata',
    'home.featured.label': 'La Nostra Selezione',
    'home.featured.title': 'Top Veicoli',
    'home.featured.subtitle': 'Selezionati a mano e controllati — i nostri ultimi modelli premium',
    'home.featured.viewAll': 'Visualizza tutti',
    'home.features.q.title': 'Qualità Controllata',
    'home.features.q.desc': 'Ogni veicolo viene sottoposto a un\'ispezione in 150 punti dai nostri esperti.',
    'home.features.c.title': 'Migliori Condizioni',
    'home.features.c.desc': 'Prezzi trasparenti e opzioni di finanziamento flessibili.',
    'home.features.g.title': 'Garanzia Inclusa',
    'home.features.g.desc': 'Protezione completa su tutti i veicoli — per la tua sicurezza.',
    'home.features.f.title': 'Finanziamento Facile',
    'home.features.f.desc': 'Rate flessibili, approvazione rapida, soluzioni personalizzate.',
    'home.phi.label': 'La Nostra Filosofia',
    'home.phi.title': 'Più che semplici automobili. La tua mobilità.',
    'home.phi.desc1': 'Nordhessen Automobile è sinonimo di trasparenza assoluta, consulenza onesta e servizio clienti di prima classe. Capiamo che l\'acquisto di un veicolo è una questione di fiducia.',
    'home.phi.desc2': 'Ogni veicolo nel nostro showroom proviene dal nostro stock attuale ed è accuratamente controllato per soddisfare i nostri elevati standard. Scopri modelli ben tenuti con una storia garantita.',
    'home.phi.live': 'Dal vivo',
    'home.phi.live_desc': 'Stock Attuale',
    'home.phi.transparency': 'Massima',
    'home.phi.transparency_desc': 'Trasparenza d\'Acquisto',
    'home.why.label': 'I Nostri Punti di Forza',
    'home.why.title': 'Perché Nordhessen Automobile?',
    'home.why.subtitle': 'Fiducia, qualità e servizio — i pilastri del nostro successo',
    'home.cta.label': 'Pronto per la tua nuova?',
    'home.cta.title1': 'La tua auto da sogno',
    'home.cta.title2': 'ti sta già aspettando.',
    'home.cta.desc': 'Scopri la nostra selezione premium e trova il veicolo perfetto che soddisfi le tue massime esigenze.',
    'home.cta.button': 'Scopri i veicoli',
    'home.no_cars': 'Attualmente non ci sono veicoli disponibili.',
    'card.year': 'Anno',
    'card.km': 'Chilometraggio',
    'card.fuel': 'Carburante',
    'card.gearbox': 'Cambio',
    'card.details': 'Vedi Dettagli',
    'scroll.elegance': 'L\'ELEGANZA INCONTRA LA PERFORMANCE',
    'scroll.elegance_desc': 'La fusione perfetta di sportività e praticità quotidiana. Una coupé a quattro porte che trasforma ogni viaggio in un\'esperienza.',
    'scroll.design': 'SCOLPITO PER L\'AERODINAMICA',
    'scroll.design_title': 'Design',
    'scroll.design_desc': 'Porte senza cornice, linea del tetto fluida e l\'iconica griglia. Ogni dettaglio progettato per tagliare l\'aria con precisione.',
    'scroll.engine': 'EFFICIENZA TURBOCOMPRESSA',
    'scroll.engine_title': 'Motore',
    'scroll.engine_desc': 'Motore potente che offre dinamica di guida pura ed efficienza in ogni viaggio. Trasmissione perfettamente abbinata per una guida esaltante.',
    'scroll.performance': 'ESPERIENZA DI GUIDA DINAMICA',
    'scroll.performance_title': 'Performance',
    'scroll.performance_desc': 'Accelerazione eccezionale e maneggevolezza precisa grazie alla tecnologia avanzata delle sospensioni M Sport e allo sterzo sportivo variabile.',
    'scroll.nav.start': 'Inizio',
    'scroll.nav.design': 'Design',
    'scroll.nav.engine': 'Motore',
    'scroll.nav.performance': 'Performance',
    'scroll.location': 'Posizione // Kassel',
    'scroll.cta.title1': 'Trova la Tua',
    'scroll.cta.title2': 'Auto da Sogno',
    'scroll.cta.desc': 'Veicoli premium, consulenza personale e servizio di prima classe. Scopri la nostra collezione attuale.',
    'scroll.cta.button': 'Tutti i Modelli',
    'scroll.cta.stat1': 'Controllato',
    'scroll.cta.stat2_val': 'Premium',
    'scroll.cta.stat2': 'Qualità',
    'scroll.cta.stat3_val': 'Top',
    'scroll.cta.stat3': 'Servizio',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const isValidLanguage = (lang: string | null): lang is Language => {
  return ['de', 'en', 'pt', 'fr', 'es', 'it'].includes(lang as string);
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('site_language');
    return isValidLanguage(saved) ? saved : 'de';
  });

  useEffect(() => {
    localStorage.setItem('site_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
